[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
lazorkit = "HKAM6aGJsNuyxoVKNk8kgqMTUNSDjA3ciZUikHYemQzL"
transfer_limit = "34eqBPLfEvFGRNDbvpZLaa791J1e1zKMcFoVp19szLjY"
default_rule = "FcHpLspZz2U5JykpRmFBjaAsfJvPZsfKSBpegNBnjFbX"

[programs.localnet]
lazorkit = "HKAM6aGJsNuyxoVKNk8kgqMTUNSDjA3ciZUikHYemQzL"
transfer_limit = "34eqBPLfEvFGRNDbvpZLaa791J1e1zKMcFoVp19szLjY"
default_rule = "FcHpLspZz2U5JykpRmFBjaAsfJvPZsfKSBpegNBnjFbX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.test.ts"
